swagger: '2.0'
info:
  title: api-gateway
  description: API Gateway
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /payments/{user_id}/payment:
    post:
      summary: The Payment Service
      operationId: payment-make-v1
      x-google-backend:
        address: https://payment-service-bmftoimaia-ew.a.run.app/
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: OK
      parameters:
        - name: "user_id"
          in: "path"
          description: "ID of the user"
          required: true
          type: "integer"
          format: "int64"
  /payments/{user_id}:
    get:
      summary: The Payment Service
      operationId: payment-get-v1
      x-google-backend:
        address: https://payment-service-bmftoimaia-ew.a.run.app/
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: OK
      parameters:
        - name: "user_id"
          in: "path"
          description: "ID of the user"
          required: true
          type: "integer"
          format: "int64"          
  /payments/pay/{user_id}:
    get:
      summary: The Payment Service
      operationId: payment-pay-v1
      x-google-backend:
        address: https://payment-service-bmftoimaia-ew.a.run.app/
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: OK
      parameters:
        - name: "user_id"
          in: "path"
          description: "ID of the user"
          required: true
          type: "integer"
          format: "int64"          
  /payments/pay/{user_id}/success:
    get:
      summary: The Payment Service
      operationId: payment-pay-success-v1
      x-google-backend:
        address: https://payment-service-bmftoimaia-ew.a.run.app/
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: OK
      parameters:
        - name: "user_id"
          in: "path"
          description: "ID of the user"
          required: true
          type: "integer"
          format: "int64"          
  /products/new/{admin_id}:
    post:
      summary: The Payment Service
      operationId: products-new-v1
      x-google-backend:
        address: https://product-service-bmftoimaia-ew.a.run.app/
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: OK
      parameters:
        - name: "admin_id"
          in: "path"
          description: "ID of the admin"
          required: true
          type: "integer"
          format: "int64"
  /products:
    get:
      summary: The Payment Service
      operationId: products-list-v1
      x-google-backend:
        address: https://product-service-bmftoimaia-ew.a.run.app/
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: OK
  /products/{product_id}:
    get:
      summary: The Payment Service
      operationId: products-detail-v1
      x-google-backend:
        address: https://product-service-bmftoimaia-ew.a.run.app/
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: OK
      parameters:
        - name: "product_id"
          in: "path"
          description: "ID of the product"
          required: true
          type: "integer"
          format: "int64"
  /products/update/amount/{admin_id}:
    post:
      summary: The Payment Service
      operationId: products-update-amount-v1
      x-google-backend:
        address: https://product-service-bmftoimaia-ew.a.run.app/
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: OK
      parameters:
        - name: "admin_id"
          in: "path"
          description: "ID of the admin"
          required: true
          type: "integer"
          format: "int64"
  /products/update/price/{admin_id}:
    post:
      summary: The Payment Service
      operationId: products-update-price-v1
      x-google-backend:
        address: https://product-service-bmftoimaia-ew.a.run.app/
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: OK
      parameters:
        - name: "admin_id"
          in: "path"
          description: "ID of the admin"
          required: true
          type: "integer"
          format: "int64"                    
  /orders:
    post:
      summary: The Order Service
      operationId: order-v1-create
      x-google-backend:
        address: https://order-service-bmftoimaia-ew.a.run.app/
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: OK
  /orders/{o_id}:
    get:
      summary: The Order Service
      operationId: order-detail-v1
      x-google-backend:
        address: https://order-service-bmftoimaia-ew.a.run.app/
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: OK
      parameters:
        - name: "o_id"
          in: "path"
          description: "ID of the order"
          required: true
          type: "integer"
          format: "int64"
  /orders/{o_id}/status:
    put:
      summary: The Order Service
      operationId: order-detail-status-v1
      x-google-backend:
        address: https://order-service-bmftoimaia-ew.a.run.app/
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: OK
      parameters:
        - name: "o_id"
          in: "path"
          description: "ID of the order"
          required: true
          type: "integer"
          format: "int64"
  /orders/{o_id}/remove:
    delete:
      summary: The Order Service
      operationId: order-detail-delete-v1
      x-google-backend:
        address: https://order-service-bmftoimaia-ew.a.run.app/
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: OK
      parameters:
        - name: "o_id"
          in: "path"
          description: "ID of the order"
          required: true
          type: "integer"
          format: "int64"                                                  
  /customers:
    post:
      summary: The Customer Service
      operationId: customer-create-v1
      x-google-backend:
        address: https://customer-service-bmftoimaia-ew.a.run.app/
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: OK
  /customers/getAll:
    post:
      summary: The Customer Service
      operationId: customer-getall-v1
      x-google-backend:
        address: https://customer-service-bmftoimaia-ew.a.run.app/
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: OK          
  /customers/{c_id}:
    get:
      summary: The Customer Service
      operationId: customer-get-v1
      x-google-backend:
        address: https://customer-service-bmftoimaia-ew.a.run.app/
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: OK
      parameters:
        - name: "c_id"
          in: "path"
          description: "ID of the customer"
          required: true
          type: "integer"
          format: "int64"
  /customers/{c_id}/delete:
    delete:
      summary: The Customer Service
      operationId: customer-delete-v1
      x-google-backend:
        address: https://customer-service-bmftoimaia-ew.a.run.app/
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: OK
      parameters:
        - name: "c_id"
          in: "path"
          description: "ID of the customer"
          required: true
          type: "integer"
          format: "int64"          
  /customers/login:
    put:
      summary: The Customer Service
      operationId: customer-login-v1
      x-google-backend:
        address: https://customer-service-bmftoimaia-ew.a.run.app/
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: OK
  /customers/{c_id}/logout:
    put:
      summary: The Customer Service
      operationId: customer-logout-v1
      x-google-backend:
        address: https://customer-service-bmftoimaia-ew.a.run.app/
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: OK
      parameters:
        - name: "c_id"
          in: "path"
          description: "ID of the customer"
          required: true
          type: "integer"
          format: "int64"
  /customers/{c_id}/update:
    put:
      summary: The Customer Service
      operationId: customer-update-v1
      x-google-backend:
        address: https://customer-service-bmftoimaia-ew.a.run.app/
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: OK
      parameters:
        - name: "c_id"
          in: "path"
          description: "ID of the customer"
          required: true
          type: "integer"
          format: "int64"
  /v1/return/new:
    post:
      summary: The Return Service
      operationId: return-create-v1
      x-google-backend:
        address: https://europe-west1-ada-return.cloudfunctions.net/ada-dev-create_return
      responses:
        '200':
          description: OK
  /v1/return:
    get:
      summary: The Return Service
      operationId: return-get-v1
      x-google-backend:
        address: https://europe-west1-ada-return.cloudfunctions.net/ada-dev-get_return
      responses:
        '200':
          description: OK
  /v1/return/all:
    get:
      summary: The Return Service
      operationId: return-get-all-v1
      x-google-backend:
        address: https://europe-west1-ada-return.cloudfunctions.net/ada-dev-get_all_returns 
      responses:
        '200':
          description: OK
  /v1/return/status:
    put:
      summary: The Return Service
      operationId: return-status-v1
      x-google-backend:
        address: https://europe-west1-ada-return.cloudfunctions.net/ada-dev-update_return_status
      responses:
        '200':
          description: OK
  /v1/return/delete:
    put:
      summary: The Return Service
      operationId: return-delete-v1
      x-google-backend:
        address: https://europe-west1-ada-return.cloudfunctions.net/ada-dev-delete_return
      responses:
        '200':
          description: OK
